# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - casapisdev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Create env
        run: cp .env.example .env

      - name: Check if .env exists
        id: check_env_created
        uses: andstor/file-existence-action@v1
        with:
          files: '.env'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: php-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'env-demo'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: php-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'casapisdev'
          slot-name: 'env-demo'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E3DB553D776B4A61AB8441A51840E7B5 }}
          package: .

      - name: Retrieve the installer using curl
        run: curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php

      - name: Verify the obtained value
        run: HASH=`curl -sS https://composer.github.io/installer.sig`

      - name: Verify Installer
        run: php -r "if (hash_file('SHA384', '/tmp/composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
      
      - name: Install composer
        run: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Run dir
        run: dir

      - name: Check if .env.example exists
        id: check_env
        uses: andstor/file-existence-action@v1
        with:
          files: '.env.example'

      - name: Create htaccess
        run: cp .htaccess.example .htaccess 
